spagobi:
    image: knowagelabs/knowage:6.1
    links:
        - knowagedb:db
    environment:
        - WAIT_MYSQL=true
        - ENABLE_HIGHCHARTS=n

spagobidb:
    image: mysql:5.5
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
